import 'public/assets/icons/logotype-white.svg'
import 'public/assets/icons/honest-development.svg'
import 'public/assets/icons/burger.svg'
import 'public/assets/icons/bookmark.svg'
import 'public/assets/icons/user.svg'
import 'public/assets/icons/arrow.svg'
import 'public/assets/icons/arrow_l.svg'
import 'public/assets/icons/arrowbutton.svg'
import 'public/assets/icons/phone.svg'

//account page
import 'public/assets/icons/stonelogo.svg'
import 'public/assets/icons/stonelogoblack.svg'
import 'public/assets/icons/empty.svg'
import 'public/assets/icons/favoritesWhite.svg'
import 'public/assets/icons/favorites.svg'
import 'public/assets/icons/meetings.svg'
import 'public/assets/icons/meetingsWhite.svg'
import 'public/assets/icons/selection.svg'
import 'public/assets/icons/selectionWhite.svg'
import 'public/assets/icons/booking.svg'
import 'public/assets/icons/bookingWhite.svg'
import 'public/assets/icons/success.svg'
import 'public/assets/icons/close.svg'
import 'public/assets/icons/arrowBack.svg'
import 'public/assets/icons/activeUser.svg'
import 'public/assets/icons/unavailable.svg'

//--

import 'public/assets/icons/stone-dom.svg'
import 'public/assets/icons/stone-office.svg'
import 'public/assets/icons/office.svg'
import 'public/assets/icons/dom.svg'

import 'public/assets/icons/responsibility.svg'
import 'public/assets/icons/responsibility_dark.svg'
import 'public/assets/icons/relationship-service.svg'
import 'public/assets/icons/empathy.svg'
import 'public/assets/icons/empathy_dark.svg'
import 'public/assets/icons/individuality.svg'
import 'public/assets/icons/individuality_dark.svg'
import 'public/assets/icons/art-concept.svg'

import 'public/assets/icons/bolt.svg'
import 'public/assets/icons/time.svg'
import 'public/assets/icons/star.svg'
import 'public/assets/icons/check.svg'
import 'public/assets/icons/simple-check.svg'
import 'public/assets/icons/mail.svg'

import 'public/assets/icons/branch.svg'

import 'public/assets/icons/double-round.svg'
import 'public/assets/icons/globe.svg'
import 'public/assets/icons/settings.svg'
import 'public/assets/icons/invest-grid.svg'
import 'public/assets/icons/invest-houses.svg'
import 'public/assets/icons/invest-home.svg'
import 'public/assets/icons/invest-bars.svg'
import 'public/assets/icons/invest-lineup.svg'
import 'public/assets/icons/invest-bars-light.svg'
import 'public/assets/icons/invest-route.svg'
import 'public/assets/icons/invest-pin.svg'
import 'public/assets/icons/invest-planing.svg'

import 'public/assets/icons/opportunities-heart.svg'
import 'public/assets/icons/opportunities-landscape.svg'
import 'public/assets/icons/opportunities-car.svg'
import 'public/assets/icons/opportunities-dog.svg'

import 'public/assets/icons/projects-bars.svg'
import 'public/assets/icons/projects-houses.svg'
import 'public/assets/icons/projects-lineup.svg'

import 'public/assets/icons/plus.svg'
import 'public/assets/icons/minus.svg'
import 'public/assets/icons/close.svg'
import 'public/assets/icons/route.svg'
import 'public/assets/icons/basketball.svg'
import 'public/assets/icons/briefcase.svg'
import 'public/assets/icons/brightness_up.svg'
import 'public/assets/icons/building.svg'
import 'public/assets/icons/food.svg'

import 'public/assets/icons/close-circle.svg'
import 'public/assets/icons/spinner.svg'

//-- testContent

import 'public/assets/icons/bookmark_black.svg'
import 'public/assets/icons/ellipse.svg'
import 'public/assets/icons/fullscreen.svg'

//standardsPages
import 'public/assets/icons/aesthetics_01.svg'
import 'public/assets/icons/aesthetics_02.svg'
import 'public/assets/icons/aesthetics_02_dark.svg'
import 'public/assets/icons/aesthetics_03.svg'
import 'public/assets/icons/aesthetics_03_dark.svg'
import 'public/assets/icons/aesthetics_04.svg'
import 'public/assets/icons/aesthetics_04_dark.svg'
