import type { Metadata } from 'next'
import 'shared/lib/utils/svgSprite'
import './ui/styles/globals.scss'
import ProvidesTheQueryClient from '../src/providers/ProvidersTheQueryClient'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ProvidesTheQueryClient>
        <body>{children}</body>
      </ProvidesTheQueryClient>
    </html>
  )
}
