import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/styles/globals.scss";
import ProvidesTheQueryClient from "./ui/providers/ProvidersTheQueryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ProvidesTheQueryClient>
        <body className={inter.className}>{children}</body>
      </ProvidesTheQueryClient>
    </html>
  );
}
