import Head from 'next/head'
import { FC } from 'react'
import { MainLayout } from 'src/layouts/MainLayout'
import { getCommon } from 'src/shared/services/pageData/common/common'
import { ICommonResponse } from 'src/shared/services/pageData/common/common.interface'

export interface IEmailProps {
  common: ICommonResponse
}

const Email: FC<IEmailProps> = ({ common }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>

      <MainLayout common={common.data.attributes} isDisplayFooter={false}></MainLayout>
    </>
  )
}

export default Email

export const getStaticPaths = () => {
  const paths = [{ params: { action: 'check' } }, { params: { action: 'unsubscribe' } }]
  return { paths, fallback: false }
}

export const getStaticProps = async () => {
  const commonData: ICommonResponse = await getCommon()

  return {
    props: {
      common: commonData,
    },
  }
}
